# Generated by Django 6.0.6 on 2026-06-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')]),
        ),
    ]
