# Generated by Django 6.0.6 on 2026-06-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blogpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
